import { faker } from "@faker-js/faker";

export const FEEDS = [
  {
    feedId: 1,
    username: "love.capybara",
    createdAt: new Date().toISOString(),
    following: false,
    content: faker.image.urlLoremFlickr(),
    text: faker.lorem.paragraphs(5),
    likes: 23,
  },
  {
    feedId: 2,
    username: "Jessie",
    createdAt: new Date().toISOString(),
    following: false,
    content: faker.image.urlLoremFlickr(),
    text: faker.lorem.paragraphs(5),
    likes: 235,
  },
  {
    feedId: 3,
    username: "Ice_cream",
    createdAt: new Date().toISOString(),
    following: false,
    content: faker.image.urlLoremFlickr(),
    text: faker.lorem.paragraphs(5),
    likes: 43,
  },
  {
    feedId: 4,
    username: "reoooo.ng",
    createdAt: new Date().toISOString(),
    following: true,
    content: faker.image.urlLoremFlickr(),
    text: faker.lorem.paragraphs(5),
    likes: 100,
  },
  {
    feedId: 5,
    username: "suzan.D",
    createdAt: new Date().toISOString(),
    following: false,
    content: faker.image.urlLoremFlickr(),
    text: faker.lorem.paragraphs(5),
    likes: 0,
  },
  {
    feedId: 6,
    username: "Peppiey",
    createdAt: new Date().toISOString(),
    following: false,
    content: faker.image.urlLoremFlickr(),
    text: faker.lorem.paragraphs(5),
    likes: 744,
  },
  {
    feedId: 7,
    username: "collean",
    createdAt: new Date().toISOString(),
    following: true,
    content: faker.image.urlLoremFlickr(),
    text: faker.lorem.paragraphs(5),
    likes: 10,
  },
  {
    feedId: 8,
    username: "mallLover",
    createdAt: new Date().toISOString(),
    following: false,
    content: faker.image.urlLoremFlickr(),
    text: faker.lorem.paragraphs(5),
    likes: 55,
  },
  {
    feedId: 9,
    username: "peace.-.-",
    createdAt: new Date().toISOString(),
    following: true,
    content: faker.image.urlLoremFlickr(),
    text: faker.lorem.paragraphs(5),
    likes: 6582,
  },
  {
    feedId: 10,
    username: "H.J",
    createdAt: new Date().toISOString(),
    following: true,
    content: faker.image.urlLoremFlickr(),
    text: faker.lorem.paragraphs(5),
    likes: 22,
  },
  {
    feedId: 11,
    username: "Adio",
    createdAt: new Date().toISOString(),
    following: false,
    content: faker.image.urlLoremFlickr(),
    text: faker.lorem.paragraphs(5),
    likes: 541,
  },
  {
    feedId: 12,
    username: "LetEatBeeee",
    createdAt: new Date().toISOString(),
    following: false,
    content: faker.image.urlLoremFlickr(),
    text: faker.lorem.paragraphs(5),
    likes: 2,
  },
  {
    feedId: 13,
    username: "Simon",
    createdAt: new Date().toISOString(),
    following: true,
    content: faker.image.urlLoremFlickr(),
    text: faker.lorem.paragraphs(5),
    likes: 0,
  },
  {
    feedId: 14,
    username: "DellaCrue",
    createdAt: new Date().toISOString(),
    following: false,
    content: faker.image.urlLoremFlickr(),
    text: faker.lorem.paragraphs(5),
    likes: 775,
  },
  {
    feedId: 15,
    username: "Musinsa",
    createdAt: new Date().toISOString(),
    following: true,
    content: faker.image.urlLoremFlickr(),
    text: faker.lorem.paragraphs(5),
    likes: 32,
  },
];
